# Generated by Django 4.1.7 on 2023-02-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0003_alter_hospitals_area_alter_hospitals_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='area',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='hospital',
            field=models.CharField(max_length=100),
        ),
    ]
