# Generated by Django 4.1.7 on 2023-02-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0005_alter_hospitals_area_alter_hospitals_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='contact',
            field=models.CharField(default='', max_length=12),
        ),
    ]
