# Generated by Django 4.1.7 on 2023-02-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0006_alter_hospitals_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='contact',
            field=models.CharField(default='', max_length=17),
        ),
    ]
