# Generated by Django 4.1.7 on 2023-02-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0007_alter_hospitals_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_age', models.CharField(max_length=5)),
                ('p_gender', models.CharField(max_length=10)),
                ('p_blood_needed', models.CharField(max_length=5)),
                ('p_reason', models.CharField(max_length=30)),
            ],
        ),
    ]
