# Generated by Django 4.1.7 on 2023-02-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0010_adminbloodrequest_p_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbloodrequest',
            name='p_age',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='adminbloodrequest',
            name='p_blood_needed',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='adminbloodrequest',
            name='p_gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='adminbloodrequest',
            name='p_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='adminbloodrequest',
            name='p_reason',
            field=models.CharField(default='', max_length=30),
        ),
    ]
