# Generated by Django 4.1.7 on 2023-02-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0014_rejectdonorlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptBloodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=30)),
                ('p_age', models.CharField(default='', max_length=5)),
                ('p_gender', models.CharField(default='', max_length=10)),
                ('p_contact', models.CharField(default='', max_length=12)),
                ('p_blood_needed', models.CharField(default='', max_length=5)),
                ('p_reason', models.CharField(default='', max_length=30)),
                ('p_location', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RejectBloodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=30)),
                ('p_age', models.CharField(default='', max_length=5)),
                ('p_gender', models.CharField(default='', max_length=10)),
                ('p_contact', models.CharField(default='', max_length=12)),
                ('p_blood_needed', models.CharField(default='', max_length=5)),
                ('p_reason', models.CharField(default='', max_length=30)),
                ('p_location', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
