# Generated by Django 4.1.7 on 2023-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0016_userdonorrequest_d_location_userdonorrequest_d_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptdonorlist',
            name='d_location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='acceptdonorlist',
            name='d_visit',
            field=models.CharField(default='', max_length=5),
        ),
    ]
