# Generated by Django 4.1.7 on 2023-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0017_acceptdonorlist_d_location_acceptdonorlist_d_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptdonorlist',
            name='d_contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userdonorrequest',
            name='d_contact',
            field=models.CharField(default='', max_length=15),
        ),
    ]
