# Generated by Django 4.1.7 on 2023-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0018_alter_acceptdonorlist_d_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectdonorlist',
            name='d_location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='rejectdonorlist',
            name='d_visit',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='acceptbloodlist',
            name='p_contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='adminbloodrequest',
            name='p_contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='rejectbloodlist',
            name='p_contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='rejectdonorlist',
            name='d_contact',
            field=models.CharField(default='', max_length=15),
        ),
    ]
