# Generated by Django 4.1.7 on 2023-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0020_alter_userdonorrequest_d_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonorrequest',
            name='d_gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
