# Generated by Django 4.1.7 on 2023-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0023_remove_rejectdonorlist_d_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptdonorlist',
            name='d_location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='acceptdonorlist',
            name='d_visit',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='rejectdonorlist',
            name='d_location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='rejectdonorlist',
            name='d_visit',
            field=models.CharField(default='', max_length=5),
        ),
    ]
