# Generated by Django 4.1.7 on 2023-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0024_acceptdonorlist_d_location_acceptdonorlist_d_visit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(default='', max_length=10)),
                ('donoraccepted', models.IntegerField()),
                ('bloodaccepted', models.IntegerField()),
                ('balance', models.CharField(max_length=100)),
            ],
        ),
    ]
