# Generated by Django 4.1.7 on 2023-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0026_alter_stocklist_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactfom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('area', models.CharField(default='', max_length=30)),
                ('comment', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
