# Generated by Django 4.1.7 on 2023-03-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0027_contactfom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactfom',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
