# Generated by Django 4.1.7 on 2023-03-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0028_alter_contactfom_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklist',
            name='balance',
        ),
    ]
