# Generated by Django 4.1.7 on 2023-03-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0029_remove_stocklist_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='balance',
            field=models.CharField(default='', max_length=10),
        ),
    ]
