# Generated by Django 4.1.7 on 2023-03-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0030_stocklist_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='links',
            field=models.URLField(default=''),
        ),
    ]
