# Generated by Django 4.1.7 on 2023-03-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0032_remove_hospitals_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockList',
        ),
    ]
