# Generated by Django 4.1.7 on 2023-03-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0033_delete_stocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='links',
            field=models.URLField(default=''),
        ),
    ]
